### ISSUE TITLE
Doesnt compile?

### ISSUE THREAD

**Issue by Bigsy** [igrishaev/virtuoso#1]
Maybe I'm doing something wrong but the lib doesnt' appear to work, always get this compiler error

```
Syntax error (NoSuchFieldException) compiling . at (virtuoso/core.clj:103:5).
newVirtualThreadPerTaskExecutor
```
Using openjdk version "21.0.5" 2024-10-15

**Comment by igrishaev** [comment]
Is this still relevant? Perhaps you really have JDK version 21 installed, but when you compile the project, lein or deps use another JVM. You can try to expose a JAVA_HOME env var like this:

```
JAVA_HOME=/path/to/java21/ lein uberjar
```

**Comment by Bigsy** [comment]
Yeah apologies, totally jumped the gun so closed it off - had set jenv for local but forgot shell so lein wasn't on 21.

Thanks 👍
